FROM php:7.4.23-zts

RUN pecl install parallel && \
	docker-php-ext-enable parallel && \
	EXTENSION_DIR=`php-config --extension-dir 2>/dev/null` && \
	echo "=====================================================================" && \
	echo "Finished building. SHA256:" && \
	sha256sum "$EXTENSION_DIR/parallel.so" | sed "s/  /\n/" && \
	echo "====================================================================="
