#!/bin/bash
set -ex

EXT="parallel"
PHP_VERSION=$(docker run $IMAGE_NAME php -r 'echo phpversion();')
PARTS=(${DOCKER_TAG//-/ })

if [[ ${PARTS[0]} = "develop" ]]; then
	BRANCH="develop"
fi

cd "${BRANCH:-release}"
UPSTREAM_COMMIT=$(git rev-parse --short HEAD)

TAGS=( "${PARTS[0]}-${PHP_VERSION}-${UPSTREAM_COMMIT}" )

if [[ ${PARTS[1]} = "7.4" ]]; then
	TAGS+=( ${PARTS[0]} )

	if [[ ${PARTS[0]} = "alpine" ]]; then
		TAGS+=( "latest" )
	fi
fi

for TAG in "${TAGS[@]}"
do
	docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
	docker push $DOCKER_REPO:$TAG
done
